# Generated by Django 3.0.5 on 2020-07-03 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_comment_content_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='content_type',
        ),
    ]
