# Generated by Django 3.0.5 on 2020-07-07 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0022_auto_20200705_1925'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='comments_count',
        ),
    ]
